# Generated by Django 6.0.7 on 2026-07-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donors", "0002_alter_donorprofile_blood_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donorprofile",
            name="is_available",
            field=models.BooleanField(default=False),
        ),
    ]
