# Generated by Django 6.0.7 on 2026-07-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donors", "0004_donation"),
    ]

    operations = [
        migrations.AddField(
            model_name="donorprofile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="donorprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("other", "Other"),
                    ("prefer_not_to_say", "Prefer not to say"),
                ],
                max_length=20,
            ),
        ),
    ]
