# Generated by Django 6.0.7 on 2026-07-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donors", "0005_donorprofile_date_of_birth_donorprofile_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("declined", "Declined"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
