# Generated by Django 6.0.7 on 2026-07-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donors", "0007_donorprofile_latitude_donorprofile_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="donorprofile",
            name="max_distance_km",
            field=models.PositiveIntegerField(default=50),
        ),
    ]
