# Generated by Django 6.0.7 on 2026-07-23 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donors", "0008_donorprofile_max_distance_km"),
    ]

    operations = [
        migrations.CreateModel(
            name="DonorHealthCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feeling_well", models.BooleanField(default=False)),
                ("no_recent_tattoo_or_piercing", models.BooleanField(default=False)),
                ("no_recent_travel_risk", models.BooleanField(default=False)),
                ("not_on_medication", models.BooleanField(default=False)),
                ("meets_weight_minimum", models.BooleanField(default=False)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "donation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_check",
                        to="donors.donation",
                    ),
                ),
            ],
        ),
    ]
