# Generated by Django 6.0.7 on 2026-07-21 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donors", "0003_alter_donorprofile_is_available"),
        ("requests_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloodrequest",
            name="matched_donor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matched_requests",
                to="donors.donorprofile",
            ),
        ),
        migrations.AlterField(
            model_name="bloodrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("in_progress", "In Progress"),
                    ("fulfilled", "Fulfilled"),
                    ("cancelled", "Cancelled"),
                ],
                default="open",
                max_length=15,
            ),
        ),
    ]
