# Generated by Django 6.0.7 on 2026-07-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests_app", "0002_bloodrequest_matched_donor_alter_bloodrequest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloodrequest",
            name="donor_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
