# Generated by Django 6.0.7 on 2026-07-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests_app", "0003_bloodrequest_donor_confirmed"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloodrequest",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
