# Generated by Django 6.0.7 on 2026-07-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospitalprofile",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
