# Generated by Django 6.0.7 on 2026-07-21 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0002_hospitalprofile_is_verified"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="hospitalprofile",
            name="license_document",
            field=models.FileField(
                blank=True, null=True, upload_to="hospital_licenses/"
            ),
        ),
        migrations.AddField(
            model_name="hospitalprofile",
            name="registration_no",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="hospitalprofile",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hospitalprofile",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hospitals_verified",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
