# Generated by Django 6.0.7 on 2026-07-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0004_alter_hospitalprofile_registration_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospitalprofile",
            name="license_document",
            field=models.FileField(
                blank=True,
                help_text="Upload hospital license document",
                null=True,
                upload_to="hospital_licenses/%Y/%m/",
            ),
        ),
        migrations.AlterField(
            model_name="hospitalprofile",
            name="registration_no",
            field=models.CharField(
                blank=True,
                help_text="Official hospital registration or license number",
                max_length=100,
                null=True,
            ),
        ),
    ]
