# Generated by Django 6.0.7 on 2026-07-21 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0005_alter_hospitalprofile_license_document_and_more"),
        ("hospitals", "0005_hospitalprofile_latitude_hospitalprofile_longitude"),
    ]

    operations = []
