# Generated by Django 6.0.7 on 2026-07-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("request_created", "Request Created"),
                    ("request_matched", "Request Matched"),
                    ("request_fulfilled", "Request Fulfilled"),
                    ("request_cancelled", "Request Cancelled"),
                    ("hospital_verified", "Hospital Verified"),
                    ("message", "New Message"),
                ],
                max_length=30,
            ),
        ),
    ]
